<div class="loadingio-spinner-ripple-c441d5t4s6j">
  <div class="ldio-r792qopq4sd">
    <div></div>
    <div></div>
  </div>
</div>

<style>
  @keyframes ldio-r792qopq4sd {
    0% {
      top: 96px;
      left: 96px;
      width: 0;
      height: 0;
      opacity: 1;
    }
    100% {
      top: 18px;
      left: 18px;
      width: 156px;
      height: 156px;
      opacity: 0;
    }
  }.ldio-r792qopq4sd div {
    position: absolute;
    border-width: 4px;
    border-style: solid;
    opacity: 1;
    border-radius: 50%;
    animation: ldio-r792qopq4sd 1.5384615384615383s cubic-bezier(0,0.2,0.8,1) infinite;
  }.ldio-r792qopq4sd div:nth-child(1) {
    border-color: #ff3e00;
    animation-delay: 0s;
  }
  .ldio-r792qopq4sd div:nth-child(2) {
    border-color: #40b3ff;
    animation-delay: -0.7692307692307692s;
  }
  .loadingio-spinner-ripple-c441d5t4s6j {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: rgba(255, 255, 255, 0);
  }
  .ldio-r792qopq4sd {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-r792qopq4sd div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>
